### ISSUE TITLE
unorm float type not recognized

### ISSUE THREAD

**Issue by mrvux** [tgjones/HlslTools#102]
Hello, one small issue I picked no long ago:
float (and float[n]) can have a unorm/snorm qualifier, so the following declarations are valid:

``` cpp
unorm float f = 1.0f;
snorm float f = 2.0f;
```

As local the qualifier does nothing, but if we want to write to an R8G8B8A8_Unorm texture in compute, we need to declare as:

``` cpp
RWTexture<unorm float4> myTexture;
```

I can see two different ways to fix it, but I'm not sure which would be the preffered one:
* Declare unorm float[n] as single declarations
* unorm/snorm to become some "type qualifier" in the syntax tree (and mark it as allowed only for float family, since unorm int is not allowed. I'm not sure if the syntax tree already supports that

I guess 1 is easier, but 2 is a bit cleaner and closer to the language.

I'm also happy to fix it once decided between 1 and 2 :)

Thanks
Julien

**Comment by mrvux** [comment]
Oops it did strip the template qualifier for RWTexture, which is 

`RWTexture < unorm float4 >`

**Comment by tgjones** [comment]
One bit of HLSL grammar I'm not sure of: if `unorm` is used, must it *always* be immediately by `float`?

If so, we could do the same as what I've already done for `unsigned int`, which is another two-token type name. That's more or less your option (1).

If `unorm` is allowed in other places than immediately preceding `float`, then we should probably do option (2). But the syntax tree doesn't already support it, so that would be a bigger change.

**Comment by mrvux** [comment]
Unorm works with float, float [N] and float[NxM] (so float and float vectors)

**Comment by tgjones** [comment]
Only took 2 years, but this is fixed now...
