### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by matt77hias** [tgjones/HlslTools#116]
- There seems to be no way of changing the color of the macro symbols. You can set the color of "identifiers", but this will bottleneck the formatting of C++ code.
- I changed all colors with a `HLSL prefix`, hovering over code, however, shows a popup with completely different colors.
- Somehow Visual Studio does not remember anymore which functions, code blocks, etc. are closed in HLSL files. When I open a HLSL file, everything is opened automatically.
- Somehow the +/- squares for opening blocks of code disappears occasionally for **C++ code**.

**Comment by tgjones** [comment]
Sorry for the huge delay in responding to this!

* "HLSL Macro Identifier" is the colour used for macro symbols.
* I've changed the hover tooltip code quite a bit since you logged this issue - it should use the same colours now.
* I've created #184 for the not-remember-outlining-expansion bug.
* This HLSL extension shouldn't have any effect at all on C++ code. If you have a reproducible case please let me know.
