### ISSUE TITLE
Unsupported and doesn't really work - is there an alternative?

### ISSUE THREAD

**Issue by xiaoguid** [tgjones/HlslTools#127]
This project seems to be deprecated/unsupported for a long time now, stopped working properly back in VS2015 and never fixed since, just got worse with every VS update.

Various long standing issues (error message boxes on *every* single file open, not recognizing language words and 1000% broken auto-complete - all logged under Issues) unfortunately render this extension completely useless.

If this project is deprecated/unsupported it should be marked as such and save all of us who keep trying to use it a lot of time.

Is there an alternative?

**Comment by tgjones** [comment]
Whilst I don't disagree with the general theme, I don't think is very helpful as an issue, because it just adds even more to an already full issues list. For discussion it would be better to use the Gitter room: https://gitter.im/tgjones/HlslTools

My personal life is very busy at the moment, so I'm not able to put much as much time into my open source projects as I'd like. If and when I do have time, I'll do more work on this project. So it's not deprecated. It's just that this project is the (unpaid) work of one person, and that's how these things go.

Pull requests are always gratefully received.
