### ISSUE TITLE
Add .usf (Unreal Engine shaders) to the list of supported extensions

### ISSUE THREAD

**Issue by inequation** [tgjones/HlslTools#25]
I work with the Unreal Engine 4 and I'd love it if I didn't have to manually change the GUID every time a HLSL Tools update arrives. ;)

Perhaps you could just add this extension to the manifest? It's not a widely used one, there is little chance of ambiguity.

**Comment by tgjones** [comment]
As @samizzo noted [here](http://timjones.tw/blog/archive/2015/10/06/introducing-hlsl-tools-for-visual-studio#comment-2529948402), I should be able to implement `IVsEditorFactory` and then have HLSL Tools show up in Tools -> Options -> Text Editor -> File Extension. (Although as noted [here](https://github.com/samizzo/nshader/blob/master/README.md), there appear to be some bugs in VS around this feature.)

**Comment by samizzo** [comment]
I'm not 100% certain that it isn't my implementation at fault, because writing VS extensions is stupidly complex! But I did find a [blog](http://weblog.west-wind.com/posts/2013/Mar/22/Text-Editor-AssociationsExtensions-in-Visual-Studio-getting-lost) post about the issue where VS kept losing the extension associations.

**Comment by tgjones** [comment]
@samizzo I've found a solution to the File > Recent Files bug. You need to add an entry to the `FileExtensionMapping` registry key, [like Roslyn does here](https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/VisualStudio/CSharp/Impl/CSharpPackageRegistration.pkgdef). I've written a `ProvideFileExtensionMapping` attribute class to do it in C# instead of a .pkgdef file.

**Comment by samizzo** [comment]
I just implemented this for NShader and I noticed that if I have both `ProvideEditorFactory` and `ProvideFileExtensionMapping` on my package, I get two entries in the drop down in Tools->Options->Text Editor->File Extension. Do you see that?

**Comment by tgjones** [comment]
If I have both `ProvideEditorExtension` and `ProvideFileExtensionMapping` on the package, then yes, I see two entries. Thanks for spotting that, I'll fix it now. (But I can have both `ProvideEditorFactory` and `ProvideFileExtensionMapping` without causing a duplicate.)

**Comment by inequation** [comment]
Hey guys, just dropping by to say I really appreciate the change. :) Thanks for making my life easier!
