### ISSUE TITLE
Line numbers for errors don't always match actual error.

### ISSUE THREAD

**Issue by reltham** [tgjones/HlslTools#7]
Getting lots of the false preprocessor errors being reported on the wrong lines.

The red underline thing seems to be right.

Additional info:
I'm seeing this in included files. Primarily ones that get included by a lot of shaders in my solution.  We have around 50 shaders and another 50 or so shader headers, many of which are included by a bunch of the shaders. I end up with dozens of the same error on the same line of the fxh files, sometimes with different line numbers.  Would be nice if the error in an include said what file it was included from.

**Comment by tgjones** [comment]
Errors in the error list now include the filename, which should fix this issue. But there are a couple of limitations with the current version:

1. You will still get duplicate errors, if you have multiple files open that all `include` the same header file, and that header has a syntax error.
2. When you fix the error in the header file, the files that `include` it won't be re-parsed until you edit them, which means the errors from the header file will remain in the error list.

Both these issues will be resolved once I complete this item from the [roadmap](https://github.com/tgjones/HlslTools/blob/master/CHANGELOG.md#roadmap):
* If `#include`d file is open file in Visual Studio, use that instead of on-disk version

**Comment by tgjones** [comment]
This is still an issue - in the error list, line and column numbers for errors in `#include`d files are completely wrong (because they're based on the `ITextSnapshot` of the root file).
